---
title: "RandomForest"
author: "Andrew Thornton"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(gbm)
library(caret)
library(tidyverse)
source('Functions.r')
source('Data_Model.r')
```

## Get and Subset Data
```{r}
df = get_data_with_success()
df_sets = subset_data(df)
StudentTrain = data.frame(df_sets[1])
StudentTest = data.frame(df_sets[2])

#Specific for GBM
StudentTrain$Success = as.numeric(StudentTrain$Success)-1
```

##RF modeling
``` {r}
set.seed(456)

boost=gbm(Success~.,data=StudentTrain,distribution="bernoulli",n.trees=100)
summary(boost)

# Predictions on the test set
rf_pred_class <- predict(boost, StudentTest, n.trees=100)
summary(rf_pred_class)

# Consistent levels
rf_pred_class = ifelse(rf_pred_class > .5, 1, 0)
rf_pred_class <- factor(rf_pred_class, levels = levels(StudentTest$Success))
saveRDS(rf_pred_class, file="gbm_test.rds")

# Confusion Matrix
rf_conf_matrix <- confusionMatrix(rf_pred_class, StudentTest$Success)
rf_conf_matrix
```