---
title: "Model Analysis"
author: "Andrew Thornton"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(randomForest)
library(stargazer)
library(class)
source("functions.r")
source("data_model.r")
library(pROC)
```
Loading True Labels
```{r}
#For KNN Specifically
df_knn = get_data_with_success()
df_sets_knn = subset_data_with_test(df_knn, .6, .5)

dftrain_knn = data.frame(df_sets_knn[1])
dfvalidation_knn = data.frame(df_sets_knn[2])
dftest_knn = data.frame(df_sets_knn[3])

#For all other models
df = get_data_with_success()
df_sets = subset_data(df)
dftrain = data.frame(df_sets[1])
dftest = data.frame(df_sets[2])
```

Loading Predictions
``` {r}
knn_train = readRDS(file = "knn_train.rds")
knn_test = readRDS(file = "knn_test.rds")
xgb_test = readRDS(file = "xgb_test.rds")
tree_test = readRDS(file = "tree_test.rds")
rforest_test = readRDS(file="rforest_test.rds")
logistic_test = readRDS(file="logistic_test.rds")
cluster = readRDS(file="cluster.rds")
bag = readRDS(file="bagging_test.rds")
gbm_test =readRDS(file="gbm_test.rds")
```

``` {r}
#roc1 <- roc(dftrain_knn$Success, as.numeric(knn_train), levels = rev(levels(dftrain_knn$Success)))
roc1 <- roc(dftest$Success, as.numeric(rforest_test), levels = rev(levels(dftest$Success)))
roc2 <- roc(dftest_knn$Success, as.numeric(knn_test), levels = rev(levels(dftest_knn$Success)))
roc3 <- roc(dftest$Success, as.numeric(xgb_test), levels = rev(levels(dftest$Success)))
roc4 <- roc(dftest$Success, as.numeric(tree_test), levels = rev(levels(dftest$Success)))
roc5 <- roc(dftest$Success, as.numeric(logistic_test), levels = rev(levels(dftest$Success)))
roc6 <- roc(df$Success, as.numeric(cluster), levels = rev(levels(df$Success)))
roc7 <- roc(dftest$Success, as.numeric(bag), levels = rev(levels(df$Success)))
roc8 <- roc(dftest$Success, as.numeric(gbm_test), levels = rev(levels(df$Success)))

plot(roc1, col = "blue", main = "ROC Curve Comparison", lwd = 2)
plot(roc2, col = "red", add = TRUE, lwd = 2)
plot(roc3, col = "orange", add = TRUE, lwd = 2)
plot(roc4, col="pink", add=TRUE, lwd = 2)
plot(roc5, col="green", add=TRUE, lwd = 2)
plot(roc6, col="brown", add=TRUE, lwd=2)
plot(roc7, col="purple", add=TRUE, lwd=2)
plot(roc8, col="black", add=TRUE, lwd=2)

legend("bottomright", legend=c("Logistic", "KNN", "Decision Tree", "Random Forest", "XGB", "K-Means Clustering", "Bagging", "GBM" ), col=c("green", "red", "pink", "blue", "orange", "brown", "purple", "black"), lwd=2)
```

```{r}
auc(roc1)
auc(roc2)
auc(roc3)
auc(roc4)
auc(roc5)
auc(roc6)
auc(roc7)
auc(roc8)
```