---
title: "RandomForest"
author: "Andrew Thornton"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(randomForest)
library(caret)
library(tidyverse)
source('Functions.r')
source('Data_Model.r')
```

## Get and Subset Data
```{r}
df = data.frame(get_data())
df_sets = subset_data_v(df, 0.6)
StudentTrain = data.frame(df_sets[1])
StudentTest = data.frame(df_sets[2])
```

##RF modeling
``` {r}
rf_model <- randomForest(GradeClass ~ ., data = StudentTrain, mtry = sqrt(ncol(StudentTrain) - 1), importance = TRUE)
summary(rf_model)

# Predictions on the test set
rf_pred_class <- predict(rf_model, StudentTest)

# Consistent levels
rf_pred_class <- factor(rf_pred_class, levels = levels(StudentTest$GradeClass))

# Confusion Matrix
rf_conf_matrix <- confusionMatrix(rf_pred_class, StudentTest$GradeClass)
print(rf_conf_matrix)

# Binary Sensitivity and Specificity Calculation
rf_pred_class_binary <- rf_pred_class == positive_class

sensitivity_rf <- sensitivity(as.factor(rf_pred_class_binary), as.factor(StudentTest_binary), positive = "TRUE")
specificity_rf <- specificity(as.factor(rf_pred_class_binary), as.factor(StudentTest_binary), positive = "TRUE")

sensitivity_rf
specificity_rf
```